apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysdig-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.sysdig.com
    chart: shield
    targetRevision: "1.43.1"
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/SimiOps/argocd-applications/main/sysdig-agent/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sysdig-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: Secret
      name: sysdig-agent-shield-cluster
      jsonPointers:
        - /data
    - kind: Secret
      name: sysdig-agent-shield-cluster-tls-certificates
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: apps
      kind: Deployment
      name: sysdig-agent-shield-cluster
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1webhook



---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: result-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Santiagososs/example-voting-app
    targetRevision: main
    path: manifests/result
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Santiagososs/example-voting-app
    targetRevision: main
    path: manifests/vote
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Santiagososs/example-voting-app
    targetRevision: main
    path: manifests/worker
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "v1.20.2"   
    helm:
      parameters:
        - name: crds.enabled      
          value: "true"
        - name: crds.keep
          value: "true"
      valuesObject:
        prometheus:
          enabled: true 
        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9402"
          prometheus.io/path: "/metrics"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: x509-certificate-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.enix.io
    chart: x509-certificate-exporter
    targetRevision: "4.1.0"    
    helm:
      valuesObject:
        secretsExporter:
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9793"
            prometheus.io/path: "/metrics"
        prometheusServiceMonitor:
          create: false
        prometheusRules:
          create: false
  destination:
    server: https://kubernetes.default.svc
    namespace: x509-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vuln-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SimiOps/argocd-applications
    targetRevision: main
    path: vuln-lab/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: vuln-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true